version: "2"
sql:
  - engine: "mysql"
    queries: "query.sql"
    schema: "migrations"
    gen:
      go:
        package: "models"
        sql_package: "database/sql"
        sql_driver: "github.com/go-sql-driver/mysql"
        out: "../internal/models"